name: main_workflow

on:

  pull_request:
    branches: [ main, test ]
    
#   workflow_dispatch

# on:
#   repository_dispatch:
#     types: [deploy-event]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/checkout@v2
        with:
          repository: 'nikil-sigmoid/source_code_demo1'
          ref: ${{ github.ref_name }}
#           ref: 'main'
          path: 'source_code/'

      - name: Docker build and run
        run: |
          echo "Current directory: `pwd`"
          tag_name="deploy_image_branch_$GITHUB_REF_NAME"
          echo "tag: $tag_name"
          docker build -t $tag_name .
          docker run $tag_name
