name: main_workflow

on:

#   push:
#     branches: [ main ]
  workflow_dispatch


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/checkout@v2
        with:
          repository: 'nikil-sigmoid/source_code_demo1'
          ref: 'test'
          path: 'source_code/'

      - name: list folders
        run: |
          echo "Current directory: `pwd`"
          docker build -t deploy_image .
          docker run deploy_image
